# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Run Automated Tests"

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies and run tests
        run: |
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99
          npm install
          touch css/custom.css
          npm run test:prettier
          npm run test:js
          npm run test:css
          npm run test:unit
          npm run test:e2e
          npm run test:electron
